# Generated by Django 3.2.19 on 2023-06-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.pet'),
        ),
    ]
