# Generated by Django 3.2.19 on 2023-06-29 18:54

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(validators=[bookings.models.validate_date_is_present_or_future]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(validators=[bookings.models.validate_date_is_present_or_future]),
        ),
    ]
