# Generated by Django 3.2.19 on 2023-07-20 17:51

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20230629_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(validators=[bookings.models.validate_date_is_future]),
        ),
    ]
